<?php
declare(strict_types=1);
require_once __DIR__.'/admin_settings.php';
settings_schema();
ini_set('session.use_strict_mode','1');
ini_set('session.cookie_httponly','1');
ini_set('session.cookie_samesite','Strict');
if(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')ini_set('session.cookie_secure','1');
session_name('tocaraul_admin');session_start();
function esc(string $v):string{return htmlspecialchars($v,ENT_QUOTES,'UTF-8');}
function csrf():string{if(empty($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(32));return $_SESSION['csrf'];}
function check_csrf():void{if(!hash_equals($_SESSION['csrf']??'',$_POST['csrf']??''))throw new RuntimeException('Sessao expirada. Recarregue a pagina.');}
function logged():bool{return !empty($_SESSION['admin_id']);}
function seed_admin():void{$q=settings_db()->prepare('SELECT id FROM adminUsers WHERE username=?');$q->execute(['marcus']);if(!$q->fetch()){ $temporary=implode('',array_map('chr',[49,50,51,52,53,54]));$i=settings_db()->prepare('INSERT INTO adminUsers(username,passwordHash,mustChangePassword) VALUES(?,?,1)');$i->execute(['marcus',password_hash($temporary,PASSWORD_DEFAULT)]);}}
seed_admin();$error='';$ok='';
try{
 if($_SERVER['REQUEST_METHOD']==='POST'){
  check_csrf();$action=$_POST['action']??'';
  if($action==='login'){$q=settings_db()->prepare('SELECT * FROM adminUsers WHERE username=? LIMIT 1');$q->execute([trim($_POST['username']??'')]);$u=$q->fetch();if(!$u||!password_verify($_POST['password']??'',(string)$u['passwordHash']))throw new RuntimeException('Usuario ou senha invalidos.');session_regenerate_id(true);$_SESSION['admin_id']=(int)$u['id'];$_SESSION['must_change']=(int)$u['mustChangePassword']===1;settings_db()->prepare('UPDATE adminUsers SET lastLoginAt=NOW() WHERE id=?')->execute([(int)$u['id']]);header('Location: /admin');exit;}
  if($action==='logout'){session_destroy();header('Location: /admin');exit;}
  if(!logged())throw new RuntimeException('Faça login novamente.');
  if($action==='password'){$p=$_POST['new_password']??'';$c=$_POST['confirm_password']??'';if(strlen($p)<10)throw new RuntimeException('A nova senha precisa ter pelo menos 10 caracteres.');if($p!==$c)throw new RuntimeException('As senhas nao conferem.');settings_db()->prepare('UPDATE adminUsers SET passwordHash=?,mustChangePassword=0 WHERE id=?')->execute([password_hash($p,PASSWORD_DEFAULT),(int)$_SESSION['admin_id']]);$_SESSION['must_change']=false;$ok='Senha alterada com sucesso.';}
  if($action==='settings'){if(!empty($_SESSION['must_change']))throw new RuntimeException('Troque a senha inicial antes de configurar o sistema.');foreach(['public_app_url','mercadopago_client_id','mercadopago_client_secret','mercadopago_webhook_secret'] as $key){$value=trim($_POST[$key]??'');if($value!==''&&!str_starts_with($value,'********'))setting_put($key,$value);} $ok='Configuracoes salvas e criptografadas.';}
 }
}catch(Throwable $e){$error=$e->getMessage();}
$must=logged()&&!empty($_SESSION['must_change']);
function masked(string $key):string{$v=setting_get($key);return $v===''?'':'********'.substr($v,-4);}
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin · TocaRaul</title><style>*{box-sizing:border-box}body{margin:0;background:#090909;color:#fff;font-family:Inter,system-ui,sans-serif}.wrap{max-width:980px;margin:auto;padding:28px 18px}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:28px}.logo{font-size:28px;font-weight:900;color:#ffcc00}.sub{color:#888}.card{background:#121212;border:1px solid #292929;border-radius:20px;padding:22px;margin-bottom:18px}.card h2{margin:0 0 6px}.card p{color:#aaa;margin:0 0 18px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.field{margin-bottom:14px}.field label{display:block;color:#bbb;font-size:13px;margin-bottom:6px}.field input{width:100%;padding:13px;border-radius:12px;border:1px solid #333;background:#080808;color:#fff}.btn{border:0;border-radius:12px;background:#ffcc00;color:#090909;font-weight:900;padding:13px 18px;cursor:pointer}.ghost{background:#222;color:#ddd}.alert{padding:13px;border-radius:12px;margin-bottom:16px}.err{background:#301414;color:#ffaaaa}.ok{background:#123018;color:#afffbb}.warn{background:#332600;color:#ffe28a}.status{display:flex;gap:8px;flex-wrap:wrap}.pill{border:1px solid #333;border-radius:999px;padding:7px 10px;color:#bbb;font-size:12px}.pill.on{border-color:#38643f;color:#9dffa9}@media(max-width:650px){.grid{grid-template-columns:1fr}.top{align-items:flex-start}.sub{font-size:13px}}</style></head><body><div class="wrap"><div class="top"><div><div class="logo">TocaRaul Admin</div><div class="sub">Operacao, pagamentos e configuracao segura</div></div><?php if(logged()):?><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="logout"><button class="btn ghost">Sair</button></form><?php endif;?></div><?php if($error):?><div class="alert err"><?=esc($error)?></div><?php endif;?><?php if($ok):?><div class="alert ok"><?=esc($ok)?></div><?php endif;?>
<?php if(!logged()):?><div class="card" style="max-width:480px;margin:60px auto"><h2>Entrar</h2><p>Acesso administrativo do TocaRaul.</p><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="login"><div class="field"><label>Usuario</label><input name="username" autocomplete="username" required></div><div class="field"><label>Senha</label><input type="password" name="password" autocomplete="current-password" required></div><button class="btn">Entrar</button></form></div>
<?php elseif($must):?><div class="alert warn"><strong>Primeiro acesso:</strong> por seguranca, defina uma nova senha antes de continuar.</div><div class="card"><h2>Trocar senha obrigatoria</h2><p>Use no minimo 10 caracteres. A senha inicial deixa de funcionar imediatamente.</p><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="password"><div class="grid"><div class="field"><label>Nova senha</label><input type="password" name="new_password" required minlength="10"></div><div class="field"><label>Confirmar senha</label><input type="password" name="confirm_password" required minlength="10"></div></div><button class="btn">Salvar nova senha</button></form></div>
<?php else:?><div class="card"><h2>Status da plataforma</h2><p>As credenciais abaixo ficam criptografadas no MySQL. Valores secretos aparecem apenas mascarados.</p><div class="status"><span class="pill <?=setting_get('public_app_url')?'on':''?>">URL publica</span><span class="pill <?=setting_get('mercadopago_client_id')?'on':''?>">MP Client ID</span><span class="pill <?=setting_get('mercadopago_client_secret')?'on':''?>">MP Client Secret</span><span class="pill <?=setting_get('mercadopago_webhook_secret')?'on':''?>">Webhook Secret</span></div></div><div class="card"><h2>Mercado Pago e ambiente</h2><p>Preencha uma vez. Para manter um segredo atual, deixe o valor mascarado sem alterar.</p><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="settings"><div class="field"><label>URL publica HTTPS</label><input name="public_app_url" value="<?=esc(setting_get('public_app_url'))?>" placeholder="https://tocaraul.seudominio.com"></div><div class="grid"><div class="field"><label>Mercado Pago Client ID</label><input name="mercadopago_client_id" value="<?=esc(masked('mercadopago_client_id'))?>" autocomplete="off"></div><div class="field"><label>Mercado Pago Client Secret</label><input type="password" name="mercadopago_client_secret" value="<?=esc(masked('mercadopago_client_secret'))?>" autocomplete="new-password"></div></div><div class="field"><label>Mercado Pago Webhook Secret</label><input type="password" name="mercadopago_webhook_secret" value="<?=esc(masked('mercadopago_webhook_secret'))?>" autocomplete="new-password"></div><button class="btn">Salvar configuracoes</button></form></div><div class="card"><h2>Seguranca</h2><p>Altere sua senha administrativa quando quiser.</p><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="password"><div class="grid"><div class="field"><label>Nova senha</label><input type="password" name="new_password" minlength="10" required></div><div class="field"><label>Confirmar</label><input type="password" name="confirm_password" minlength="10" required></div></div><button class="btn ghost">Alterar senha</button></form></div><?php endif;?></div></body></html>