<?php
declare(strict_types=1);
require_once __DIR__ . '/../api_config.php';
function settings_db(): PDO { static $pdo=null; if($pdo instanceof PDO)return $pdo; return $pdo=new PDO('mysql:host='.DB_HOST.';dbname='.DB_NAME.';charset=utf8mb4',DB_USER,DB_PASS,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]); }
function settings_schema(): void { $db=settings_db(); $db->exec("CREATE TABLE IF NOT EXISTS adminUsers (id int AUTO_INCREMENT PRIMARY KEY,username varchar(80) NOT NULL UNIQUE,passwordHash varchar(255) NOT NULL,mustChangePassword tinyint(1) NOT NULL DEFAULT 1,lastLoginAt timestamp NULL,createdAt timestamp DEFAULT CURRENT_TIMESTAMP,updatedAt timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"); $db->exec("CREATE TABLE IF NOT EXISTS systemSettings (settingKey varchar(120) PRIMARY KEY,encryptedValue longtext NOT NULL,updatedAt timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"); }
function settings_key(): string { static $key=null; if(is_string($key))return $key; $path=dirname(__DIR__).'/.tocaraul_admin.key'; if(is_file($path)){ $raw=file_get_contents($path); if(is_string($raw)&&strlen($raw)===32)return $key=$raw; throw new RuntimeException('Invalid master key'); } $raw=random_bytes(32); if(file_put_contents($path,$raw,LOCK_EX)===false)throw new RuntimeException('Could not create master key'); @chmod($path,0600); return $key=$raw; }
function settings_encrypt(string $value): string { if($value==='')return ''; $iv=random_bytes(12);$tag='';$cipher=openssl_encrypt($value,'aes-256-gcm',settings_key(),OPENSSL_RAW_DATA,$iv,$tag);if($cipher===false)throw new RuntimeException('Encryption failed');return base64_encode($iv.$tag.$cipher); }
function settings_decrypt(string $value): string { if($value==='')return ''; $raw=base64_decode($value,true);if($raw===false||strlen($raw)<29)return ''; $plain=openssl_decrypt(substr($raw,28),'aes-256-gcm',settings_key(),OPENSSL_RAW_DATA,substr($raw,0,12),substr($raw,12,16));return is_string($plain)?$plain:''; }
function setting_get(string $name): string { settings_schema();$q=settings_db()->prepare('SELECT encryptedValue FROM systemSettings WHERE settingKey=?');$q->execute([$name]);$row=$q->fetch();return $row?settings_decrypt((string)$row['encryptedValue']):''; }
function setting_put(string $name,string $value): void { settings_schema();$q=settings_db()->prepare('INSERT INTO systemSettings(settingKey,encryptedValue) VALUES(?,?) ON DUPLICATE KEY UPDATE encryptedValue=VALUES(encryptedValue),updatedAt=CURRENT_TIMESTAMP');$q->execute([$name,settings_encrypt(trim($value))]); }
