<?php
declare(strict_types=1);
require_once __DIR__.'/admin_settings.php';
header('Content-Type: application/json; charset=utf-8');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Headers: Authorization, Content-Type, X-Request-Id, X-Signature');
header('Access-Control-Allow-Methods: GET, POST, OPTIONS');
if(($_SERVER['REQUEST_METHOD']??'')==='OPTIONS'){http_response_code(204);exit;}
function db():PDO{return settings_db();}
function out(array $p,int $s=200):never{http_response_code($s);echo json_encode($p,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function input():array{$v=json_decode(file_get_contents('php://input')?:'{}',true);return is_array($v)?$v:[];}
function bearer():string{$h=$_SERVER['HTTP_AUTHORIZATION']??'';return stripos($h,'Bearer ')===0?trim(substr($h,7)):'';}
function device():array{$t=bearer();if($t==='')out(['message'=>'Device token required'],401);$q=db()->prepare("SELECT * FROM devices WHERE deviceToken=? AND status<>'REVOKED' LIMIT 1");$q->execute([$t]);$d=$q->fetch();if(!$d||empty($d['venueId']))out(['message'=>'Activated device required'],401);return$d;}
function schema():void{$d=db();$d->exec("CREATE TABLE IF NOT EXISTS financeLedger(id bigint AUTO_INCREMENT PRIMARY KEY,venueId int NOT NULL,requestId int NULL,paymentId int NULL,type varchar(30) NOT NULL,grossCents int NOT NULL DEFAULT 0,barCents int NOT NULL DEFAULT 0,platformCents int NOT NULL DEFAULT 0,taxCents int NOT NULL DEFAULT 0,feeCents int NOT NULL DEFAULT 0,payoutId bigint NULL,createdAt timestamp DEFAULT CURRENT_TIMESTAMP,INDEX(venueId,payoutId,type),UNIQUE KEY uniq_request_credit(requestId,type)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");$d->exec("CREATE TABLE IF NOT EXISTS payouts(id bigint AUTO_INCREMENT PRIMARY KEY,venueId int NOT NULL,amountCents int NOT NULL,feeCents int NOT NULL DEFAULT 0,netCents int NOT NULL,pixKeySnapshot varchar(180) NOT NULL,status varchar(30) NOT NULL DEFAULT 'PENDING',provider varchar(40) NULL,providerTxId varchar(180) NULL,createdAt timestamp DEFAULT CURRENT_TIMESTAMP,paidAt timestamp NULL,INDEX(venueId,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");$d->exec("CREATE TABLE IF NOT EXISTS barPlaylist(id int AUTO_INCREMENT PRIMARY KEY,venueId int NOT NULL,providerId varchar(255) NOT NULL,title varchar(255) NOT NULL,artist varchar(255) NOT NULL,position int NOT NULL DEFAULT 0,status varchar(20) NOT NULL DEFAULT 'QUEUED',createdAt timestamp DEFAULT CURRENT_TIMESTAMP,updatedAt timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX(venueId,status,position)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");$d->exec("CREATE TABLE IF NOT EXISTS tvCommands(id bigint AUTO_INCREMENT PRIMARY KEY,venueId int NOT NULL,command varchar(20) NOT NULL,status varchar(20) NOT NULL DEFAULT 'PENDING',createdAt timestamp DEFAULT CURRENT_TIMESTAMP,executedAt timestamp NULL,INDEX(venueId,status,id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");}
function mp(string $method,string $path,?array $body=null,?string $idem=null):array{$token=runtime_mp_access_token();if($token==='')throw new RuntimeException('Configure o Access Token do Mercado Pago em /admin');$ch=curl_init('https://api.mercadopago.com'.$path);$headers=['Authorization: Bearer '.$token,'Accept: application/json','Content-Type: application/json'];if($idem)$headers[]='X-Idempotency-Key: '.$idem;curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_HTTPHEADER=>$headers,CURLOPT_CONNECTTIMEOUT=>10,CURLOPT_TIMEOUT=>25]);if($body!==null)curl_setopt($ch,CURLOPT_POSTFIELDS,json_encode($body,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));$raw=curl_exec($ch);if($raw===false){$e=curl_error($ch);curl_close($ch);throw new RuntimeException('Falha ao conectar Mercado Pago: '.$e);}$status=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);curl_close($ch);$data=json_decode($raw,true);if(!is_array($data))$data=[];if($status<200||$status>299)throw new RuntimeException('Mercado Pago '.$status.': '.($data['message']??$data['error']??'erro'));return$data;}
function sig_ok(string $id):bool{$secret=runtime_mp_webhook_secret();$sig=(string)($_SERVER['HTTP_X_SIGNATURE']??'');$rid=(string)($_SERVER['HTTP_X_REQUEST_ID']??'');if($secret===''||$sig==='')return false;$ts='';$v1='';foreach(explode(',',$sig)as$p){[$k,$v]=array_pad(explode('=',trim($p),2),2,'');if($k==='ts')$ts=$v;if($k==='v1')$v1=$v;}if($ts===''||$v1==='')return false;$m=($id!==''?'id:'.strtolower($id).';':'').($rid!==''?'request-id:'.$rid.';':'').'ts:'.$ts.';';return hash_equals(hash_hmac('sha256',$m,$secret),$v1);}
function mp_status(string $s):string{return match($s){'approved'=>'APPROVED','rejected'=>'REJECTED','cancelled','canceled'=>'CANCELLED',default=>'PENDING'};}
function nextpos(PDO$d,int$v):int{$q=$d->prepare("SELECT COALESCE(MAX(queuePosition),0)+1 n FROM songRequests WHERE venueId=? AND status IN('QUEUED','PLAYING')");$q->execute([$v]);return(int)($q->fetch()['n']??1);}
function credit_ledger(PDO$d,array$r,int$paymentId):void{$gross=(int)$r['amountCents'];$platformPct=runtime_platform_percent();$platform=(int)round($gross*$platformPct/100);$bar=$gross-$platform;$q=$d->prepare("INSERT IGNORE INTO financeLedger(venueId,requestId,paymentId,type,grossCents,barCents,platformCents) VALUES(?,?,?,'SALE',?,?,?)");$q->execute([(int)$r['venueId'],(int)$r['id'],$paymentId,$gross,$bar,$platform]);}
schema();$method=$_SERVER['REQUEST_METHOD']??'GET';$path=parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH)?:'/';
try{
if($method==='GET'&&$path==='/api/commerce/health'){db()->query('SELECT 1');out(['ok'=>true,'database'=>'online','paymentProvider'=>'mercadopago','paymentConfigured'=>runtime_mp_access_token()!==''&&runtime_mp_webhook_secret()!=='','platformPercent'=>runtime_platform_percent()]);}
if($method==='POST'&&$path==='/api/commerce/request'){$p=input();$qr=trim((string)($p['qrToken']??''));$provider=trim((string)($p['providerId']??''));$title=trim((string)($p['title']??''));$artist=trim((string)($p['artist']??''));$msg=trim((string)($p['message']??''));$name=trim((string)($p['visitorName']??'Cliente'));if($qr===''||$provider===''||$title===''||$artist==='')out(['message'=>'Dados do pedido incompletos'],400);$d=db();$q=$d->prepare("SELECT vt.*,v.musicPriceCents,v.dedicationPriceCents FROM venueTables vt JOIN venues v ON v.id=vt.venueId WHERE vt.qrToken=? AND vt.status='ACTIVE' LIMIT 1");$q->execute([$qr]);$t=$q->fetch();if(!$t)out(['message'=>'Mesa nao encontrada'],404);$amount=(int)$t['musicPriceCents']+($msg!==''?(int)$t['dedicationPriceCents']:0);$q=$d->prepare("INSERT INTO songRequests(venueId,visitorName,tableCode,providerId,title,artist,message,amountCents,status) VALUES(?,?,?,?,?,?,?,?, 'AWAITING_PAYMENT')");$q->execute([(int)$t['venueId'],$name?:'Cliente',(string)$t['label'],$provider,$title,$artist,$msg?:null,$amount]);$rid=(int)$d->lastInsertId();try{$m=mp('POST','/v1/payments',['transaction_amount'=>$amount/100,'description'=>'TocaRaul: '.$title.' - '.$artist,'payment_method_id'=>'pix','external_reference'=>'tocaraul_'.$rid,'notification_url'=>runtime_public_url().'/api/mercadopago/webhook','payer'=>['email'=>'pagamento@tocaraul.app'],'metadata'=>['tocaraul_request_id'=>$rid,'tocaraul_venue_id'=>(int)$t['venueId']]],'tocaraul-'.$rid);}catch(Throwable$e){$d->prepare("UPDATE songRequests SET status='FAILED' WHERE id=?")->execute([$rid]);throw$e;}$ext=(string)($m['id']??'');$pix=(string)($m['point_of_interaction']['transaction_data']['qr_code']??'');if($ext===''||$pix==='')throw new RuntimeException('Mercado Pago nao retornou o Pix');$q=$d->prepare("INSERT INTO payments(requestId,provider,externalId,status,amountCents,pixCopyPaste) VALUES(?,'mercadopago',?,?,?,?)");$q->execute([$rid,$ext,mp_status((string)($m['status']??'')),$amount,$pix]);out(['requestId'=>$rid,'paymentId'=>(int)$d->lastInsertId(),'externalId'=>$ext,'amountCents'=>$amount,'pixCopyPaste'=>$pix,'status'=>'AWAITING_PAYMENT'],201);}
if($method==='GET'&&$path==='/api/commerce/payment'){$rid=(int)($_GET['requestId']??0);$q=db()->prepare("SELECT p.id paymentId,p.status paymentStatus,p.amountCents,r.status requestStatus FROM payments p JOIN songRequests r ON r.id=p.requestId WHERE p.requestId=? ORDER BY p.id DESC LIMIT 1");$q->execute([$rid]);$x=$q->fetch();if(!$x)out(['message'=>'Pagamento nao encontrado'],404);out($x);}
if($method==='POST'&&$path==='/api/mercadopago/webhook'){$p=input();$id=(string)($_GET['data_id']??$_GET['data.id']??($p['data']['id']??''));if($id==='')out(['message'=>'id ausente'],400);if(!sig_ok($id))out(['message'=>'assinatura invalida'],401);$d=db();$q=$d->prepare("SELECT p.*,r.* FROM payments p JOIN songRequests r ON r.id=p.requestId WHERE p.externalId=? LIMIT 1");$q->execute([$id]);$row=$q->fetch();if(!$row)out(['ok'=>true,'ignored'=>true]);$m=mp('GET','/v1/payments/'.rawurlencode($id));$status=mp_status((string)($m['status']??''));$d->beginTransaction();try{$q=$d->prepare('SELECT * FROM payments WHERE id=? FOR UPDATE');$q->execute([(int)$row['id']]);$pay=$q->fetch();$q=$d->prepare('SELECT * FROM songRequests WHERE id=? FOR UPDATE');$q->execute([(int)$row['requestId']]);$req=$q->fetch();if(!$pay||!$req)throw new RuntimeException('Pagamento inconsistente');if($status==='APPROVED'){$d->prepare("UPDATE payments SET status='APPROVED' WHERE id=?")->execute([(int)$pay['id']]);if($req['status']==='AWAITING_PAYMENT'){$d->prepare("UPDATE songRequests SET status='QUEUED',queuePosition=? WHERE id=?")->execute([nextpos($d,(int)$req['venueId']),(int)$req['id']]);credit_ledger($d,$req,(int)$pay['id']);}}elseif($status==='REJECTED'){$d->prepare("UPDATE payments SET status='REJECTED' WHERE id=?")->execute([(int)$pay['id']]);$d->prepare("UPDATE songRequests SET status='FAILED' WHERE id=? AND status='AWAITING_PAYMENT'")->execute([(int)$req['id']]);}elseif($status==='CANCELLED'){$d->prepare("UPDATE payments SET status='CANCELLED' WHERE id=?")->execute([(int)$pay['id']]);$d->prepare("UPDATE songRequests SET status='CANCELLED' WHERE id=? AND status='AWAITING_PAYMENT'")->execute([(int)$req['id']]);}$d->commit();}catch(Throwable$e){$d->rollBack();throw$e;}out(['ok'=>true,'status'=>$status]);}
if($method==='POST'&&$path==='/api/player/claim'){$dev=device();$vid=(int)$dev['venueId'];$d=db();$d->beginTransaction();try{$q=$d->prepare("SELECT * FROM songRequests WHERE venueId=? AND status='PLAYING' ORDER BY updatedAt LIMIT 1 FOR UPDATE");$q->execute([$vid]);$r=$q->fetch();if(!$r){$q=$d->prepare("SELECT * FROM songRequests WHERE venueId=? AND status='QUEUED' ORDER BY queuePosition,createdAt LIMIT 1 FOR UPDATE");$q->execute([$vid]);$r=$q->fetch();if($r){$d->prepare("UPDATE songRequests SET status='PLAYING' WHERE id=?")->execute([(int)$r['id']]);}}if($r){$track=['id'=>(string)$r['id'],'providerId'=>$r['providerId'],'title'=>$r['title'],'artist'=>$r['artist'],'message'=>$r['message'],'tableCode'=>$r['tableCode'],'source'=>'PAID'];}else{$q=$d->prepare("SELECT * FROM barPlaylist WHERE venueId=? AND status='PLAYING' ORDER BY updatedAt LIMIT 1 FOR UPDATE");$q->execute([$vid]);$b=$q->fetch();if(!$b){$q=$d->prepare("SELECT * FROM barPlaylist WHERE venueId=? AND status='QUEUED' ORDER BY position,id LIMIT 1 FOR UPDATE");$q->execute([$vid]);$b=$q->fetch();if($b)$d->prepare("UPDATE barPlaylist SET status='PLAYING' WHERE id=?")->execute([(int)$b['id']]);}$track=$b?['id'=>(string)(-(int)$b['id']),'providerId'=>$b['providerId'],'title'=>$b['title'],'artist'=>$b['artist'],'message'=>null,'tableCode'=>null,'source'=>'BAR']:null;}$d->commit();}catch(Throwable$e){$d->rollBack();throw$e;}out(['track'=>$track]);}
if($method==='POST'&&$path==='/api/player/complete'){$dev=device();$p=input();$id=(int)($p['requestId']??0);$result=strtoupper((string)($p['result']??'PLAYED'));if(!in_array($result,['PLAYED','SKIPPED'],true)||$id===0)out(['message'=>'Conclusao invalida'],400);if($id>0){$q=db()->prepare("UPDATE songRequests SET status=? WHERE id=? AND venueId=? AND status='PLAYING'");$q->execute([$result,$id,(int)$dev['venueId']]);}else{$q=db()->prepare("UPDATE barPlaylist SET status=? WHERE id=? AND venueId=? AND status='PLAYING'");$q->execute([$result,abs($id),(int)$dev['venueId']]);}out(['ok'=>true]);}
if($method==='POST'&&$path==='/api/player/command'){$dev=device();$d=db();$d->beginTransaction();try{$q=$d->prepare("SELECT * FROM tvCommands WHERE venueId=? AND status='PENDING' ORDER BY id LIMIT 1 FOR UPDATE");$q->execute([(int)$dev['venueId']]);$cmd=$q->fetch();if($cmd)$d->prepare("UPDATE tvCommands SET status='EXECUTED',executedAt=NOW() WHERE id=?")->execute([(int)$cmd['id']]);$d->commit();}catch(Throwable$e){$d->rollBack();throw$e;}out(['command'=>$cmd?$cmd['command']:null]);}
out(['message'=>'Not found'],404);
}catch(Throwable$e){error_log('[TocaRaul] '.$e->getMessage());out(['message'=>$e->getMessage()],500);}