<?php
declare(strict_types=1);require_once __DIR__.'/admin_settings.php';require_once __DIR__.'/asaas.php';$path=parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH)?:'/';if(!preg_match('~^/j/([A-Za-z0-9_-]{6,40})$~',$path,$m)){http_response_code(404);exit('QR invalido');}$token=$m[1];$q=settings_db()->prepare("SELECT vt.label,v.name venueName,v.logoPath,v.musicPriceCents,v.dedicationPriceCents FROM venueTables vt JOIN venues v ON v.id=vt.venueId WHERE vt.qrToken=? AND vt.status='ACTIVE' LIMIT 1");$q->execute([$token]);$t=$q->fetch();if(!$t){http_response_code(404);exit('QR nao encontrado');}$name=htmlspecialchars((string)$t['venueName'],ENT_QUOTES,'UTF-8');$barLogo=(string)($t['logoPath']??'');if(!preg_match('#^/assets/logos/[A-Za-z0-9_.-]+$#',$barLogo))$barLogo='/assets/tocaraul_logo.png';$label='Pedidos do bar';$music=(int)$t['musicPriceCents'];$ded=(int)$t['dedicationPriceCents'];$ready=asaas_ready();function h($s){return htmlspecialchars((string)$s,ENT_QUOTES,'UTF-8');}header('Content-Type:text/html;charset=utf-8');?>
<!doctype html><html lang=pt-BR><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title><?=$name?> · TocaRaul</title><style>*{box-sizing:border-box}body{margin:0;background:#090909;color:#fff;font-family:system-ui;font-size:19px}.wrap{max-width:720px;margin:auto;padding:20px 16px 100px}.topbar{display:flex;align-items:center;justify-content:center;margin-bottom:4px}.logo{display:flex;align-items:center;gap:12px}.logo img{height:92px;width:92px;object-fit:contain;filter:drop-shadow(0 2px 14px rgba(255,204,0,.35))}.logo span{font-size:44px;font-weight:900;color:#ffcc00;letter-spacing:.5px}.tablechip{text-align:center;margin-bottom:6px}.chip{display:inline-block;background:#171717;border:1px solid #333;border-radius:999px;padding:10px 16px;font-size:18px;font-weight:700}.hero{margin:22px 0}.hero h1{font-size:38px;margin:0;line-height:1.1}.hero p{font-size:20px}
.steps{display:flex;gap:8px;margin:18px 0}.step-dot{flex:1;text-align:center;padding:10px 4px;border-radius:10px;background:#171717;color:#666;font-size:14px;font-weight:800}.step-dot.active{background:#241d04;color:#ffcc00;border:1px solid #ffcc00}.step-dot.done{color:#9dffa9}
.stepview{display:none}.stepview.on{display:block}
.grid{display:grid;gap:10px}.song,.card{background:#121212;border:1px solid #292929;border-radius:18px;padding:18px}.song{color:#fff;text-align:left;width:100%;min-width:0;display:flex;align-items:center;gap:12px;font-size:19px;padding:12px;cursor:pointer}.song.selected{border-color:#ffcc00;border-width:2px}.song span{color:#999;font-size:17px}.song b{color:#ffcc00;font-size:20px;flex-shrink:0}.song img{width:64px;height:64px;border-radius:10px;object-fit:cover;flex-shrink:0;background:#070707}.song .info{flex:1;min-width:0}.song .info strong{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.song .info span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.preview{width:38px;height:38px;border-radius:50%;background:#000;border:1px solid #444;color:#ffcc00;font-size:15px;flex-shrink:0;display:flex;align-items:center;justify-content:center;padding:0}
#previewBox{display:none}.preview{display:none!important}.song:after{content:'Escolher';background:#c94a40;color:#fff;border-radius:5px;padding:8px 10px;font-size:14px;font-weight:800;white-space:nowrap}
.chosen{display:flex;align-items:center;gap:12px;margin-bottom:16px;background:#0c0c0c;border:1px solid #292929;border-radius:14px;padding:12px}.chosen img{width:56px;height:56px;border-radius:10px;object-fit:cover;flex-shrink:0}.chosen .info{flex:1;min-width:0}.chosen .info strong{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.chosen .info span{color:#999;font-size:16px}
.card h2{font-size:24px}.field{margin-top:14px}.field label{display:block;color:#ccc;font-size:16px;margin-bottom:6px}input,textarea{width:100%;background:#070707;color:#fff;border:1px solid #333;border-radius:12px;padding:15px;font-size:19px}textarea{min-height:80px}.total{display:flex;justify-content:space-between;font-size:26px;font-weight:900;margin-top:15px}.btn{width:100%;border:0;border-radius:13px;background:#ffcc00;color:#090909;padding:18px;font-weight:900;margin-top:15px;font-size:21px}.btn:disabled{opacity:.4}.btn.ghost{background:#222;color:#ffcc00;border:1px dashed #ffcc00}
.pixbadge{display:flex;align-items:center;gap:14px;background:#0d1f1d;border:1px solid #1f4a45;border-radius:14px;padding:14px;margin-bottom:14px}.pixlogo{background:#fff;border-radius:8px;padding:8px 10px;flex-shrink:0;line-height:0}.pixlogo img{display:block;width:92px;height:auto}.pixbadge b{color:#32BCAD;font-size:19px}.pixbadge small{color:#8fd6cf;display:block;font-size:14px;margin-top:2px}
.secure{display:flex;align-items:center;gap:8px;color:#9dffa9;font-size:15px;margin:14px 0 0}
.qr{background:#fff;padding:12px;width:256px;margin:15px auto}.copy{word-break:break-all;background:#070707;padding:10px;border-radius:10px;color:#aaa;font-size:16px}.good{color:#aaffb3;font-size:20px}.bad{color:#ff9292;font-size:18px}</style><style>body{background:#f7f5f0;color:#242424;font-family:Arial,sans-serif}.wrap{max-width:680px}.topbar{justify-content:flex-start;margin-bottom:18px}.logo img{height:58px;width:58px;background:#e6b93f;border:2px solid #242424;border-radius:50%;filter:none;padding:4px}.logo span{font-size:28px;color:#242424;letter-spacing:-.03em}.tablechip{text-align:left}.chip{background:#fffdf7;color:#242424;border:1px solid #d8d3ca;border-radius:6px;padding:7px 11px;font-size:14px}.hero h1{font-size:34px;color:#242424}.hero p{font-size:18px;color:#5f5a52}.step-dot{background:#ece8df;color:#777;border-radius:6px}.step-dot.active{background:#e6b93f;color:#242424;border:1px solid #242424}.card,.song{background:#fffdf7;color:#242424;border:1px solid #d8d3ca;border-radius:8px;box-shadow:0 3px 12px rgba(36,36,36,.07)}.song b{color:#c94a40}.song.selected{border-color:#c94a40}.chosen{background:#f1eee7;border:1px solid #d8d3ca;border-radius:8px}input,textarea{background:#fff;color:#242424;border:1px solid #bdb7ac;border-radius:6px}.btn{background:#c94a40;color:#fff;border:1px solid #9f3029;border-radius:6px;box-shadow:none}.btn.ghost{background:#fffdf7;color:#4169a1;border:1px solid #4169a1}.pixbadge{background:#f1eee7;border:1px solid #d8d3ca;border-radius:8px}.secure,.good{color:#237f75}.copy{background:#f1eee7;color:#5f5a52;border:1px solid #d8d3ca;border-radius:6px}.bad{color:#b33d35}</style></head><body><div class=wrap>
<style>
.wrap{padding-top:28px}.hero{margin:28px 0 20px}.hero h1{font-size:40px;letter-spacing:-.04em}.hero p{margin-top:10px}
.steps{margin:20px 0 12px}.step-dot{padding:12px 6px}.step-dot.active{font-size:15px}
#view1{background:#fffdf7;border:1px solid #d8d3ca;border-radius:10px;padding:20px;box-shadow:0 5px 18px rgba(36,36,36,.08)}
#view1 .field{margin-top:0}#view1 .field label{font-size:18px;font-weight:800;color:#242424;margin-bottom:9px}
#search{font-size:20px;padding:17px 16px;border:2px solid #242424;box-shadow:inset 0 0 0 2px #fff}
#catalog{margin-top:16px}.song{min-height:88px;padding:12px 14px}.song:after{font-size:15px;padding:9px 12px}.song.selected{background:#fff4cf}
#toStep2{margin-top:18px}.topbar{margin-bottom:8px}
</style><div class=topbar><div class=logo><img src="<?=h($barLogo)?>" alt="<?=h($name)?>"><span><?=h($name)?></span></div></div><div class=tablechip><span class=chip><?=$label?></span></div>
<div class=hero><h1>Escolha. Pague. Tocou.</h1><p><?=$name?> · música <b id=base></b></p></div>
<?php if(!$ready):?><p class=bad>Cobranças sandbox ainda não configuradas pelo TocaRaul.</p><?php endif;?>
<div class=steps><div class="step-dot active" id=dot1>1 · Música</div><div class=step-dot id=dot2>2 · Seus dados</div><div class=step-dot id=dot3>3 · Pagamento</div></div>
<div id=view1 class="stepview on">
<div class=field><label>1. Busque e escolha sua música</label><input id=search placeholder="Digite o nome da música ou artista" autocomplete=off></div><p class=muted>Toque em uma música da lista para selecioná-la.</p>
<div id=catalog class=grid></div>
<button id=toStep2 class=btn disabled>Continuar</button>
</div>
<div id=view2 class=stepview>
<div class=card><h2>Seu pedido</h2><div id=chosenSummary class=chosen></div>
<div class=field><label>Nome</label><input id=visitor maxlength=80></div>
<div class=field><label>Dedicatória opcional (<?=$ded>0?'+ '.htmlspecialchars(number_format($ded/100,2,',','.'),ENT_QUOTES,'UTF-8'):'grátis'?>)</label><textarea id=message maxlength=180></textarea></div>
<div class=total><span>Total</span><span id=total></span></div>
<button id=pay class=btn <?=!$ready?'disabled':''?>>Gerar Pix</button>
<p id=error class=bad></p>
<button id=backTo1 type=button class="btn ghost">← Trocar música</button>
</div>
</div>
<div id=view3 class=stepview>
<div class=card>
<div class=pixbadge><div class=pixlogo><img src="/assets/pix_logo.svg" alt="Pix"></div><div><b>Pagamento via Pix</b><small>Sistema instantâneo do Banco Central do Brasil</small></div></div>
<div id=pixqr class=qr></div>
<div id=code class=copy></div>
<button id=copy class=btn>Copiar Pix</button>
<p class=secure>🔒 Ambiente seguro — o TocaRaul não vê nem guarda seus dados bancários, tudo passa direto pelo Pix.</p>
<p id=status>Aguardando confirmação...</p>
<button id=mockconfirm class="btn ghost">🧪 Já paguei (confirmar sandbox)</button>
</div>
</div>
</div>
<script src="/assets/qrcode.js"></script><script>
const token=<?=json_encode($token)?>,music=<?=$music?>,dedication=<?=$ded?>,ready=<?=$ready?'true':'false'?>;
let selected=null,requestId=null,searchTimer=null;const money=c=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(c/100);base.textContent=money(music);
function showStep(n){[1,2,3].forEach(i=>{document.getElementById('view'+i).classList.toggle('on',i===n);const d=document.getElementById('dot'+i);d.classList.toggle('active',i===n);d.classList.toggle('done',i<n)});window.scrollTo(0,0)}
function renderResults(list){catalog.innerHTML='';if(!list.length){catalog.innerHTML='<p style="color:#999">Nenhum resultado. Tente outro termo.</p>';return}list.forEach(s=>{let b=document.createElement('div');b.className='song'+(selected&&selected.id===s.id?' selected':'');b.setAttribute('role','button');b.setAttribute('tabindex','0');let img=document.createElement('img');img.src=s.thumbnail||'';img.alt='';let info=document.createElement('div');info.className='info';let strong=document.createElement('strong');strong.textContent=s.title;let artistSpan=document.createElement('span');artistSpan.textContent=s.artist;info.append(strong,artistSpan);let choose=document.createElement('span');choose.className='choose';choose.textContent=selected&&selected.id===s.id?'Selecionada':'Escolher';let price=document.createElement('b');price.textContent=money(music);b.append(img,info,choose,price);b.onclick=()=>{selected=s;renderResults(list);toStep2.disabled=false};catalog.appendChild(b)})}
function refresh(){total.textContent=money(music+(message.value.trim()?dedication:0));pay.disabled=!ready||!selected}
message.oninput=refresh;refresh();
try{visitor.value=localStorage.getItem('tocaraul_visitor')||''}catch(e){}
search.oninput=()=>{clearTimeout(searchTimer);const term=search.value.trim();if(term.length<2){catalog.innerHTML='';return}searchTimer=setTimeout(async()=>{catalog.innerHTML='<p style="color:#999">Buscando...</p>';try{let r=await fetch('/api/commerce/search?q='+encodeURIComponent(term)+'&qrToken='+encodeURIComponent(token));let d=await r.json();if(!r.ok){catalog.innerHTML='<p class=bad>'+(d.message||'Busca indisponível.')+'</p>';return}renderResults(d.results||[])}catch(e){catalog.innerHTML='<p class=bad>Busca indisponível no momento.</p>'}},400)};
function renderChosen(){chosenSummary.innerHTML='';if(!selected)return;let img=document.createElement('img');img.src=selected.thumbnail||'';img.alt='';let info=document.createElement('div');info.className='info';let strong=document.createElement('strong');strong.textContent=selected.title;let span=document.createElement('span');span.textContent=selected.artist;info.append(strong,span);chosenSummary.append(img,info)}
toStep2.onclick=()=>{if(!selected)return;renderChosen();refresh();showStep(2)};
backTo1.onclick=()=>{showStep(1)};
pay.onclick=async()=>{if(!selected)return;error.textContent='';pay.disabled=true;try{try{localStorage.setItem('tocaraul_visitor',visitor.value)}catch(e){}let r=await fetch('/api/commerce/request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({qrToken:token,visitorName:visitor.value||'Cliente',providerId:selected.id,title:selected.title,artist:selected.artist,message:message.value})});let d=await r.json();if(!r.ok)throw Error(d.message||'Erro ao gerar Pix');requestId=d.requestId;code.textContent=d.pixCopyPaste;pixqr.innerHTML='';new QRCode(pixqr,{text:d.pixCopyPaste,width:232,height:232});showStep(3);poll()}catch(e){error.textContent=e.message;pay.disabled=!ready}};
async function poll(){try{let r=await fetch('/api/commerce/payment?requestId='+requestId,{cache:'no-store'}),d=await r.json();if(r.ok&&(d.paymentStatus==='APPROVED'||['QUEUED','PLAYING','PLAYED'].includes(d.requestStatus))){document.getElementById('status').innerHTML='<b class=good>Pagamento confirmado. Sua música entrou na fila.</b>';mockconfirm.style.display='none';return}}catch(e){}setTimeout(poll,4000)}copy.onclick=async()=>{await navigator.clipboard.writeText(code.textContent);copy.textContent='Pix copiado'};
mockconfirm.onclick=async()=>{mockconfirm.disabled=true;mockconfirm.textContent='Confirmando...';try{await fetch('/api/commerce/mock-confirm',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId})})}catch(e){}mockconfirm.disabled=false;mockconfirm.textContent='🧪 Já paguei (confirmar sandbox)'};
</script></body></html>
